server:
  port: 8081 # Đứng gác ở cổng 8081 đúng như Gateway đã chỉ đường

spring:
  application:
    name: identity-service
  
  # Cấu hình "Cắm ống nước" xuống MySQL trong Docker
  datasource:
    url: jdbc:mysql://localhost:3306/identity_db?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # RẤT QUAN TRỌNG: Đặt là 'validate' vì chúng ta đã tự tay tạo bảng bằng file SQL (02-create-tables.sql)
      # Nó sẽ chỉ kiểm tra xem code Java có khớp với bảng MySQL không chứ không tự động xóa/tạo lại bảng.
      ddl-auto: validate 
    show-sql: true # Bật cái này lên để xem các câu lệnh SQL mà Hibernate tự động sinh ra dưới log
  
jwt:
  private-key: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCDC7qeVDMxDvgdnY6lDylwAGJ4XPh3/Gmf+irTR3pLUj30bs67h5oba/C9G6Mce0g85Q/ah9Dbswnj0R8+P+D6CedvAknl7VxwOi6fqsmhK6DbS9Jeuo9RigkClH0zVI3z2SANmOZ3BTV66K9T+xUzBdcTPm2eJ/5mz7Lj2LKLt3JGJw/WAAZkVjUqLmgVlywYZpqlT8E5KgSmzucayBNqYSoDlh8BHHTLJkqg1CM3l/7mBfHyzaVnm8W/pWXPqR5ioVJtk8jchkIMF2o8NwYC73Z3c+JiKoQtukQDH+/0VIldZP6dNCkjUVt+I5r9hAPB8SKEH2xf8yua4Fefok+pAgMBAAECggEAQRjU+eyyx1Z7y15mqzjmaTRPtiHc7eGt6KHhnzW9Guh+TUu0F3ULiT6sBozRkIbvQgy5vOFFz7VXHtvVrNsXm63K0RqucfDgwAEvAvLYmV7uV7GJDbSYGDW9NxJjRVnl8DG2GfsP1ST5xZYL7mhmRgPLLMyQsIWGezUG1Odi/kMLIIXXTj/uSRy2u0EdDtbhbHqF0iJreipSC4AKoqk0/6ll29as9/Q20OXYvws7eb80Pl93UGflZwYRUF1sPnprIv3iyxDPfJvJu085onrYnxKwZ4JdhqRZCdOfeogWXNV1WczXmD1BF+cSDtJdQaIK2XTWU4sIxoyxhVcpaXhdzwKBgQC2qzA0Il6D9g4pcWHC9EM4kW1vn5KmmV15QieHJ6/67mUTjj/FrUf0XuxBrVMpEKogVkuHcamDqlnvk9uMLdJRSH2hCTOtv2zG/I/FaJwB9Zl1QO1XYI59bMCC7XlEg4HjMbmscZKcqHNnojmDXgFCu+IxlWqrO+kFk3suT46GwwKBgQC3p0VaW7gW2JaIVb2AXWLHnlwZqpxWADP+t3evgcRFACa2LgbkziAqf1p2f5aU+wKY/hQyLeN/0pxYwbdHlZMdgMwTXR7arkr5jFLoY1u0vtYP2m8eC7QJQMaZjLUwwk9JuKwFi0Gah+E6YDLcRfyIOsYVaYHnFNwCSf5cJDJhIwKBgH5ssKoEd4HBVD/elxjE0ZlfHWy59leToZwA6zahgyyavh3wv7ZinYBGCiHSgdHUFMrYruGJCxdzWVd07+hu9jcHgttncPr5l6GIv0CTjBXXE2SRkTJ+Q2APWpXDIcEHe2fwzF7LI/uEoorBPijrcNftDTnf/bmRd09CqWh961jdAoGAG6iXa0pQ6S/pS9MN3R0zWTjiSgNF1DXnnr7myYnTk0i4i8tWwnLAqWXQq/P/K6S5+WyaggwjLQb9AOj7v04pf9H76hamJO0G4Zpeih0cnJX5Cx4sievdS190CYAFcbhx1Hp5fcRBNxKruuzt+/qWU7X2Sxc+txyPHdEi+6F/7N0CgYEApYk6iz4rlpRIBOkMZ13DsZqZMGdnvUwDdrVv4zD98W85TDVStWRLYQAAYuAf0MQrwLVYESmmdT6MBKC/qO66k+45Z4sT+0nqGGR6AOcyqSO1njy0D1Y6ZNSxX2a00V1ouyRDzMVr/egXpDgS0nXRog9ihp9zy/9F3SaRGpK+rkc="
  public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgwu6nlQzMQ74HZ2OpQ8pcABieFz4d/xpn/oq00d6S1I99G7Ou4eaG2vwvRujHHtIPOUP2ofQ27MJ49EfPj/g+gnnbwJJ5e1ccDoun6rJoSug20vSXrqPUYoJApR9M1SN89kgDZjmdwU1euivU/sVMwXXEz5tnif+Zs+y49iyi7dyRicP1gAGZFY1Ki5oFZcsGGaapU/BOSoEps7nGsgTamEqA5YfARx0yyZKoNQjN5f+5gXx8s2lZ5vFv6Vlz6keYqFSbZPI3IZCDBdqPDcGAu92d3PiYiqELbpEAx/v9FSJXWT+nTQpI1FbfiOa/YQDwfEihB9sX/MrmuBXn6JPqQIDAQAB"