server:
  port: 8082

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:mysql://localhost:3306/wallet_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root  
  jpa:
    hibernate:
      ddl-auto: update # Tự động map Entity xuống Table
    show-sql: true # Bật lên để xem Hibernate sinh câu lệnh SQL (rất hữu ích khi debug)

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: wallet-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.payment
        spring.json.use.type.headers: true
        spring.json.type.mapping: com.payment.transaction_service.event.TransferRequestedEvent:com.payment.wallet_service.event.TransferRequestedEvent,com.payment.transaction_service.event.TransferRollbackRequestedEvent:com.payment.wallet_service.event.TransferRollbackRequestedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

app:
  kafka:
    topics:
      transfer-requested: txn.transfer.requested
      transfer-completed: txn.transfer.completed
      transfer-rollback-requested: txn.transfer.rollback.requested
      transfer-rollback-completed: txn.transfer.rollback.completed